// document actions;
export const LOAD_DOCS_REQUEST = 'LOAD_DOCS_REQUEST';
export const LOAD_DOCS_SUCCESS = 'LOAD_DOCS_SUCCESS';
export const LOAD_DOCS_ERROR = 'LOAD_DOCS_ERROR';

export const EMPTY_DOCS = 'EMPTY_DOCS';

export const LOAD_SINGLE_DOC_REQUEST = 'LOAD_SINGLE_DOC_REQUEST';
export const LOAD_SINGLE_DOC_SUCCESS = 'LOAD_SINGLE_DOC_SUCCESS';
export const LOAD_SINGLE_DOC_ERROR = 'LOAD_SINGLE_DOC_ERROR';

export const SELECT_TAG = 'SELECT_TAG';